import os.log
import PassKit
import UIKit

/// UI-extension view controller for Wallet-initiated authentication
/// (P0-2 §4.7, UI extension half). Apple's two-extension architecture
/// (DEV-4.0 §10) pairs this UI extension with the non-UI
/// `PKIssuerProvisioningExtensionHandler` — when `status()` reports
/// `requiresAuthentication = true`, Wallet invokes this class inside its own
/// UI rather than redirecting to the host app.
///
/// Consumer apps subclass this with a thin brand subclass auto-generated by
/// the config plugin:
///
/// ```swift
/// import react_native_wallet_extension_auth
/// @objc(DarbWalletAuthExtension)
/// class DarbWalletAuthExtension: WalletAuthorizationProvidingViewController {}
/// ```
///
/// **Iteration 2: inline phone + OTP sign-in.** Mirrors the host RN app's
/// `darbpay-mobile/hooks/use-login-flow.ts` flow + UI: the same phone-code
/// sign-in (`signIn.create` → `prepareFirstFactor` → `attemptFirstFactor`),
/// the same `mapClerkError` mapping for human-readable inline errors, the
/// same 90s resend cooldown, the same auto-submit on a 6-digit OTP. Talks to
/// Clerk's Frontend API directly because the extension can't link the RN
/// Clerk SDK. On success, writes a JWT-template token to `SharedKeychain` and
/// reports `.authorized` so Wallet re-polls the provisioning extension.
@available(iOS 14.0, *)
@objc open class WalletAuthorizationProvidingViewController: UIViewController, PKIssuerProvisioningExtensionAuthorizationProviding {

  // `PKIssuerProvisioningExtensionAuthorizationProviding` requirement. Wallet
  // assigns this before presenting the VC; we invoke it exactly once.
  public var completionHandler: ((PKIssuerProvisioningExtensionAuthorizationResult) -> Void)?

  private static let log = OSLog(
    subsystem: Bundle.main.bundleIdentifier ?? "react-native-wallet-extension-auth",
    category: "auth-ui"
  )

  // MARK: - State (mirrors useLoginFlow)

  private enum Phase { case phone, otp }
  private var phase: Phase = .phone
  private var selectedCountry: Country = LOGIN_COUNTRIES[0]
  private var phoneDigits: String = ""
  private var otpValue: String = ""
  private var errorMessage: String?
  private var isSubmitting: Bool = false
  private var cooldown: Int = 0
  private var prepared: ClerkFrontendClient.PreparedSignIn?
  private var didComplete = false

  private let client = ClerkFrontendClient()
  private var cooldownTimer: Timer?

  // MARK: - Views

  // Heading icons — logo for phone phase, hidden in OTP phase (logo also
  // appears at the top of OTP heading block separately).
  private let phoneLogoView = DarbLogoView()
  private let otpLogoView = DarbLogoView()
  private let languagePill = LanguagePill()
  private let backButton: UIButton = {
    let b = UIButton(type: .system)
    let cfg = UIImage.SymbolConfiguration(pointSize: 18, weight: .semibold)
    b.setImage(UIImage(systemName: "chevron.left", withConfiguration: cfg), for: .normal)
    b.tintColor = DarbColors.foreground
    return b
  }()

  private let phoneTitle: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 21.5, weight: .bold)
    l.textColor = DarbColors.foreground
    l.numberOfLines = 0
    l.textAlignment = .left
    l.text = LoginCopy.phoneScreenTitle
    return l
  }()

  private let phoneSubtitle: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 16, weight: .regular)
    l.textColor = DarbColors.mutedForeground
    l.numberOfLines = 0
    l.textAlignment = .left
    l.text = LoginCopy.phoneScreenSubtitle
    return l
  }()

  private let otpTitle: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 21.5, weight: .bold)
    l.textColor = DarbColors.foreground
    l.numberOfLines = 0
    l.textAlignment = .center
    l.text = LoginCopy.enterVerificationCode
    return l
  }()

  private let otpSubtitle: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 16, weight: .regular)
    l.textColor = DarbColors.mutedForeground
    l.numberOfLines = 0
    l.textAlignment = .center
    l.text = LoginCopy.otpInstruction
    return l
  }()

  private let otpPhoneLabel: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 17, weight: .regular)
    l.textColor = DarbColors.mutedForeground
    l.textAlignment = .center
    return l
  }()

  private lazy var phoneInputRow = PhoneInputRow(
    onCountryTap: { [weak self] in self?.pickCountry() },
    onTextChange: { [weak self] in self?.phoneChanged() }
  )

  private lazy var otpCellsView: OtpCellsView = {
    let v = OtpCellsView(length: OTP_LENGTH)
    v.onChange = { [weak self] value in self?.otpChanged(value) }
    return v
  }()

  private lazy var primaryButton: PillButton = {
    let b = PillButton()
    b.title = LoginCopy.continueLabel
    b.addTarget(self, action: #selector(primaryTapped), for: .touchUpInside)
    return b
  }()

  private let phoneErrorLabel: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 14, weight: .regular)
    l.textColor = DarbColors.destructive
    l.numberOfLines = 0
    l.textAlignment = .left
    return l
  }()

  private let otpErrorLabel: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 14, weight: .regular)
    l.textColor = DarbColors.destructive
    l.numberOfLines = 0
    l.textAlignment = .center
    return l
  }()

  private let resendLabel: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 14, weight: .medium)
    l.textAlignment = .center
    l.numberOfLines = 1
    l.isUserInteractionEnabled = true
    return l
  }()

  private let spinner: UIActivityIndicatorView = {
    let s = UIActivityIndicatorView(style: .medium)
    s.hidesWhenStopped = true
    return s
  }()

  // Phase-grouping containers so we can toggle visibility wholesale.
  private let phoneContainer = UIView()
  private let otpContainer = UIView()

  // "Done" toolbar shared by the phone field and the hidden OTP field —
  // numberPad has no return key, so without this the keyboard can't be
  // dismissed. On the phone screen, tapping Done also submits when the entered
  // phone is the right length (matches the "complete keyboard now that
  // dismisses keyboard and submits" flow the user asked for).
  private lazy var dismissToolbar: UIToolbar = {
    let bar = UIToolbar()
    bar.barStyle = .default
    bar.sizeToFit()
    let flex = UIBarButtonItem(barButtonSystemItem: .flexibleSpace, target: nil, action: nil)
    let done = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(doneTapped))
    bar.items = [flex, done]
    return bar
  }()

  // MARK: - Lifecycle

  open override func viewDidLoad() {
    super.viewDidLoad()
    view.backgroundColor = DarbColors.background

    // If no publishable key was provisioned, there's nothing this UI can do —
    // bail gracefully so Wallet falls back to "open the app".
    guard ClerkFrontendClient.isConfigured else {
      os_log("auth UI not configured (no publishable key) → canceled", log: Self.log, type: .error)
      finish(.canceled)
      return
    }

    buildLayout()
    wireGestures()

    phoneInputRow.setInputAccessoryView(dismissToolbar)
    otpCellsView.setInputAccessoryView(dismissToolbar)

    render()
  }

  open override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    // becomeFirstResponder() from viewDidLoad can silently no-op because the
    // view isn't in a window yet. Re-arm focus once the wallet host has
    // actually presented us.
    switch phase {
    case .phone: _ = phoneInputRow.becomeFirstResponder()
    case .otp: _ = otpCellsView.becomeFirstResponder()
    }
  }

  deinit {
    cooldownTimer?.invalidate()
  }

  // MARK: - Layout

  private func buildLayout() {
    phoneContainer.translatesAutoresizingMaskIntoConstraints = false
    otpContainer.translatesAutoresizingMaskIntoConstraints = false
    primaryButton.translatesAutoresizingMaskIntoConstraints = false
    spinner.translatesAutoresizingMaskIntoConstraints = false
    view.addSubview(phoneContainer)
    view.addSubview(otpContainer)
    view.addSubview(primaryButton)
    view.addSubview(spinner)

    let safe = view.safeAreaLayoutGuide
    NSLayoutConstraint.activate([
      phoneContainer.topAnchor.constraint(equalTo: safe.topAnchor),
      phoneContainer.leadingAnchor.constraint(equalTo: safe.leadingAnchor),
      phoneContainer.trailingAnchor.constraint(equalTo: safe.trailingAnchor),
      phoneContainer.bottomAnchor.constraint(equalTo: primaryButton.topAnchor, constant: -8),

      otpContainer.topAnchor.constraint(equalTo: safe.topAnchor),
      otpContainer.leadingAnchor.constraint(equalTo: safe.leadingAnchor),
      otpContainer.trailingAnchor.constraint(equalTo: safe.trailingAnchor),
      otpContainer.bottomAnchor.constraint(equalTo: safe.bottomAnchor),

      primaryButton.leadingAnchor.constraint(equalTo: safe.leadingAnchor, constant: 20),
      primaryButton.trailingAnchor.constraint(equalTo: safe.trailingAnchor, constant: -20),
      primaryButton.heightAnchor.constraint(equalToConstant: 56),
      // Continue button is pinned to the safe-area bottom and stays there even
      // when the keyboard is up — the user dismisses + submits via the input
      // accessory Done button.
      primaryButton.bottomAnchor.constraint(equalTo: safe.bottomAnchor, constant: -24),

      spinner.centerXAnchor.constraint(equalTo: view.centerXAnchor),
      spinner.bottomAnchor.constraint(equalTo: primaryButton.topAnchor, constant: -12),
    ])

    buildPhonePhase()
    buildOtpPhase()
  }

  private func buildPhonePhase() {
    let topBar = UIView()
    topBar.translatesAutoresizingMaskIntoConstraints = false
    languagePill.translatesAutoresizingMaskIntoConstraints = false
    topBar.addSubview(languagePill)

    phoneLogoView.translatesAutoresizingMaskIntoConstraints = false
    let logoBox = UIView()
    logoBox.translatesAutoresizingMaskIntoConstraints = false
    logoBox.addSubview(phoneLogoView)

    let headingStack = UIStackView(arrangedSubviews: [phoneTitle, phoneSubtitle])
    headingStack.axis = .vertical
    headingStack.spacing = 8
    headingStack.alignment = .fill
    headingStack.translatesAutoresizingMaskIntoConstraints = false

    let phoneInputRowWrapper = UIView()
    phoneInputRowWrapper.translatesAutoresizingMaskIntoConstraints = false
    phoneInputRow.translatesAutoresizingMaskIntoConstraints = false
    phoneInputRowWrapper.addSubview(phoneInputRow)

    phoneErrorLabel.translatesAutoresizingMaskIntoConstraints = false

    phoneContainer.addSubview(topBar)
    phoneContainer.addSubview(logoBox)
    phoneContainer.addSubview(headingStack)
    phoneContainer.addSubview(phoneInputRowWrapper)
    phoneContainer.addSubview(phoneErrorLabel)

    NSLayoutConstraint.activate([
      topBar.topAnchor.constraint(equalTo: phoneContainer.topAnchor, constant: 10),
      topBar.leadingAnchor.constraint(equalTo: phoneContainer.leadingAnchor, constant: 20),
      topBar.trailingAnchor.constraint(equalTo: phoneContainer.trailingAnchor, constant: -20),
      topBar.heightAnchor.constraint(greaterThanOrEqualToConstant: 36),

      languagePill.trailingAnchor.constraint(equalTo: topBar.trailingAnchor),
      languagePill.centerYAnchor.constraint(equalTo: topBar.centerYAnchor),
      languagePill.topAnchor.constraint(greaterThanOrEqualTo: topBar.topAnchor),
      languagePill.bottomAnchor.constraint(lessThanOrEqualTo: topBar.bottomAnchor),

      logoBox.topAnchor.constraint(equalTo: topBar.bottomAnchor, constant: 36),
      logoBox.leadingAnchor.constraint(equalTo: phoneContainer.leadingAnchor, constant: 20),
      logoBox.trailingAnchor.constraint(equalTo: phoneContainer.trailingAnchor, constant: -20),

      phoneLogoView.centerXAnchor.constraint(equalTo: logoBox.centerXAnchor),
      phoneLogoView.topAnchor.constraint(equalTo: logoBox.topAnchor),
      phoneLogoView.bottomAnchor.constraint(equalTo: logoBox.bottomAnchor),
      phoneLogoView.widthAnchor.constraint(equalToConstant: 120),
      phoneLogoView.heightAnchor.constraint(equalToConstant: 48),

      headingStack.topAnchor.constraint(equalTo: logoBox.bottomAnchor, constant: 40),
      headingStack.leadingAnchor.constraint(equalTo: phoneContainer.leadingAnchor, constant: 20),
      headingStack.trailingAnchor.constraint(equalTo: phoneContainer.trailingAnchor, constant: -20),

      phoneInputRowWrapper.topAnchor.constraint(equalTo: headingStack.bottomAnchor, constant: 28),
      phoneInputRowWrapper.leadingAnchor.constraint(equalTo: phoneContainer.leadingAnchor, constant: 20),
      phoneInputRowWrapper.trailingAnchor.constraint(equalTo: phoneContainer.trailingAnchor, constant: -20),

      phoneInputRow.topAnchor.constraint(equalTo: phoneInputRowWrapper.topAnchor),
      phoneInputRow.leadingAnchor.constraint(equalTo: phoneInputRowWrapper.leadingAnchor),
      phoneInputRow.trailingAnchor.constraint(equalTo: phoneInputRowWrapper.trailingAnchor),
      phoneInputRow.bottomAnchor.constraint(equalTo: phoneInputRowWrapper.bottomAnchor),

      phoneErrorLabel.topAnchor.constraint(equalTo: phoneInputRowWrapper.bottomAnchor, constant: 8),
      phoneErrorLabel.leadingAnchor.constraint(equalTo: phoneContainer.leadingAnchor, constant: 20),
      phoneErrorLabel.trailingAnchor.constraint(equalTo: phoneContainer.trailingAnchor, constant: -20),
      phoneErrorLabel.heightAnchor.constraint(greaterThanOrEqualToConstant: 20),
    ])
  }

  private func buildOtpPhase() {
    let topBar = UIView()
    topBar.translatesAutoresizingMaskIntoConstraints = false
    backButton.translatesAutoresizingMaskIntoConstraints = false
    topBar.addSubview(backButton)

    otpLogoView.translatesAutoresizingMaskIntoConstraints = false
    let logoBox = UIView()
    logoBox.translatesAutoresizingMaskIntoConstraints = false
    logoBox.addSubview(otpLogoView)

    let headingStack = UIStackView(arrangedSubviews: [otpTitle, otpSubtitle, otpPhoneLabel])
    headingStack.axis = .vertical
    headingStack.spacing = 8
    headingStack.alignment = .fill
    headingStack.setCustomSpacing(4, after: otpSubtitle)
    headingStack.translatesAutoresizingMaskIntoConstraints = false

    let otpRowWrapper = UIView()
    otpRowWrapper.translatesAutoresizingMaskIntoConstraints = false
    otpCellsView.translatesAutoresizingMaskIntoConstraints = false
    otpRowWrapper.addSubview(otpCellsView)

    otpErrorLabel.translatesAutoresizingMaskIntoConstraints = false
    resendLabel.translatesAutoresizingMaskIntoConstraints = false

    otpContainer.addSubview(topBar)
    otpContainer.addSubview(logoBox)
    otpContainer.addSubview(headingStack)
    otpContainer.addSubview(otpRowWrapper)
    otpContainer.addSubview(otpErrorLabel)
    otpContainer.addSubview(resendLabel)

    NSLayoutConstraint.activate([
      topBar.topAnchor.constraint(equalTo: otpContainer.topAnchor, constant: 10),
      topBar.leadingAnchor.constraint(equalTo: otpContainer.leadingAnchor, constant: 20),
      topBar.trailingAnchor.constraint(equalTo: otpContainer.trailingAnchor, constant: -20),
      topBar.heightAnchor.constraint(greaterThanOrEqualToConstant: 36),

      backButton.leadingAnchor.constraint(equalTo: topBar.leadingAnchor),
      backButton.centerYAnchor.constraint(equalTo: topBar.centerYAnchor),
      backButton.widthAnchor.constraint(equalToConstant: 28),
      backButton.heightAnchor.constraint(equalToConstant: 28),

      logoBox.topAnchor.constraint(equalTo: topBar.bottomAnchor, constant: 36),
      logoBox.leadingAnchor.constraint(equalTo: otpContainer.leadingAnchor, constant: 20),
      logoBox.trailingAnchor.constraint(equalTo: otpContainer.trailingAnchor, constant: -20),

      otpLogoView.centerXAnchor.constraint(equalTo: logoBox.centerXAnchor),
      otpLogoView.topAnchor.constraint(equalTo: logoBox.topAnchor),
      otpLogoView.bottomAnchor.constraint(equalTo: logoBox.bottomAnchor),
      otpLogoView.widthAnchor.constraint(equalToConstant: 120),
      otpLogoView.heightAnchor.constraint(equalToConstant: 48),

      headingStack.topAnchor.constraint(equalTo: logoBox.bottomAnchor, constant: 40),
      headingStack.leadingAnchor.constraint(equalTo: otpContainer.leadingAnchor, constant: 20),
      headingStack.trailingAnchor.constraint(equalTo: otpContainer.trailingAnchor, constant: -20),

      otpRowWrapper.topAnchor.constraint(equalTo: headingStack.bottomAnchor, constant: 28),
      otpRowWrapper.leadingAnchor.constraint(equalTo: otpContainer.leadingAnchor, constant: 20),
      otpRowWrapper.trailingAnchor.constraint(equalTo: otpContainer.trailingAnchor, constant: -20),

      otpCellsView.topAnchor.constraint(equalTo: otpRowWrapper.topAnchor),
      otpCellsView.centerXAnchor.constraint(equalTo: otpRowWrapper.centerXAnchor),
      otpCellsView.bottomAnchor.constraint(equalTo: otpRowWrapper.bottomAnchor),
      otpCellsView.leadingAnchor.constraint(greaterThanOrEqualTo: otpRowWrapper.leadingAnchor),
      otpCellsView.trailingAnchor.constraint(lessThanOrEqualTo: otpRowWrapper.trailingAnchor),

      otpErrorLabel.topAnchor.constraint(equalTo: otpRowWrapper.bottomAnchor, constant: 12),
      otpErrorLabel.leadingAnchor.constraint(equalTo: otpContainer.leadingAnchor, constant: 20),
      otpErrorLabel.trailingAnchor.constraint(equalTo: otpContainer.trailingAnchor, constant: -20),
      otpErrorLabel.heightAnchor.constraint(greaterThanOrEqualToConstant: 20),

      resendLabel.topAnchor.constraint(equalTo: otpErrorLabel.bottomAnchor, constant: 8),
      resendLabel.leadingAnchor.constraint(equalTo: otpContainer.leadingAnchor, constant: 20),
      resendLabel.trailingAnchor.constraint(equalTo: otpContainer.trailingAnchor, constant: -20),
    ])
  }

  private func wireGestures() {
    backButton.addTarget(self, action: #selector(backTapped), for: .touchUpInside)
    resendLabel.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(resendTapped)))
  }

  // MARK: - Render

  private func render() {
    switch phase {
    case .phone:
      phoneContainer.isHidden = false
      otpContainer.isHidden = true
      primaryButton.isHidden = false

      phoneInputRow.country = selectedCountry
      phoneInputRow.setFormattedText(formatPhoneByCountry(phoneDigits, selectedCountry.code))
      phoneErrorLabel.text = errorMessage
      let ready = phoneDigits.count == selectedCountry.digits && !isSubmitting
      primaryButton.setEnabledState(ready)
      primaryButton.setLoading(isSubmitting)
      _ = phoneInputRow.becomeFirstResponder()
    case .otp:
      phoneContainer.isHidden = true
      otpContainer.isHidden = false
      primaryButton.isHidden = true

      otpPhoneLabel.text = isolatedPhone()
      otpErrorLabel.text = errorMessage
      otpCellsView.setText(otpValue)
      otpCellsView.setEnabled(!isSubmitting)
      renderResendLabel()
      _ = otpCellsView.becomeFirstResponder()
    }
  }

  private func renderResendLabel() {
    if cooldown > 0 {
      resendLabel.text = String(format: LoginCopy.resendCodeAfter, formatTimer(cooldown))
      resendLabel.textColor = DarbColors.foreground
    } else {
      resendLabel.text = LoginCopy.resendCode
      resendLabel.textColor = DarbColors.primary
    }
  }

  private func isolatedPhone() -> String {
    // Wrap in LRI / PDI so the leading "+" stays on the left even on RTL OSes.
    "\u{2066}\(selectedCountry.code)\(phoneDigits)\u{2069}"
  }

  // MARK: - Actions

  private func pickCountry() {
    // `.alert` style (not `.actionSheet`) because action sheets are unreliable
    // inside the PassKit auth extension's hosting environment — they
    // occasionally fail to present without error. The alert form always works.
    let picker = UIAlertController(title: "Country", message: nil, preferredStyle: .alert)
    for country in LOGIN_COUNTRIES {
      picker.addAction(UIAlertAction(title: "\(country.flag)  \(country.code)", style: .default) { [weak self] _ in
        guard let self else { return }
        self.selectedCountry = country
        self.phoneDigits = ""
        self.errorMessage = nil
        self.render()
      })
    }
    picker.addAction(UIAlertAction(title: "Cancel", style: .cancel))
    present(picker, animated: true)
  }

  private func phoneChanged() {
    let raw = phoneInputRow.rawDigits
    phoneDigits = String(raw.prefix(selectedCountry.digits))
    if errorMessage != nil { errorMessage = nil }
    // Reformat the visible value (display "5X XXX XXXX"-style).
    phoneInputRow.setFormattedText(formatPhoneByCountry(phoneDigits, selectedCountry.code))
    let ready = phoneDigits.count == selectedCountry.digits && !isSubmitting
    primaryButton.setEnabledState(ready)
    phoneErrorLabel.text = nil
  }

  private func otpChanged(_ value: String) {
    otpValue = String(value.filter(\.isNumber).prefix(OTP_LENGTH))
    if errorMessage != nil { errorMessage = nil; otpErrorLabel.text = nil }
    if otpValue.count == OTP_LENGTH, !isSubmitting {
      verifyCode()
    }
  }

  @objc private func primaryTapped() {
    sendCode()
  }

  @objc private func backTapped() {
    phase = .phone
    otpValue = ""
    errorMessage = nil
    stopCooldownTimer()
    cooldown = 0
    render()
  }

  @objc private func resendTapped() {
    guard cooldown == 0, phase == .otp, !isSubmitting else { return }
    resendCode()
  }

  /// Phone-pad has no Return key — the input-accessory Done button is the
  /// only way to dismiss the keyboard. On the phone screen, when the entered
  /// number is the right length, Done also submits (per user request: "dismiss
  /// keyboard and submit").
  @objc private func doneTapped() {
    view.endEditing(true)
    if phase == .phone, !isSubmitting, phoneDigits.count == selectedCountry.digits {
      sendCode()
    }
  }

  // MARK: - Flow

  private func sendCode() {
    guard phoneDigits.count == selectedCountry.digits else { return }
    let identifier = "\(selectedCountry.code)\(phoneDigits)"
    setSubmitting(true)
    errorMessage = nil
    phoneErrorLabel.text = nil

    Task {
      do {
        let prepared = try await client.createSignIn(identifier: identifier)
        try await client.prepareFirstFactor(signInId: prepared.signInId, phoneNumberId: prepared.phoneNumberId)
        await MainActor.run {
          self.prepared = prepared
          self.phase = .otp
          self.otpValue = ""
          self.errorMessage = nil
          self.setSubmitting(false)
          self.startCooldownTimer(seconds: 90)
          self.render()
        }
      } catch {
        await self.showError(error, fallback: LoginCopy.failedToSendCode)
      }
    }
  }

  private func verifyCode() {
    guard let prepared, otpValue.count == OTP_LENGTH else { return }
    let code = otpValue
    setSubmitting(true)
    errorMessage = nil
    otpErrorLabel.text = nil

    Task {
      do {
        let sessionId = try await client.attemptFirstFactor(signInId: prepared.signInId, code: code)
        let token = try await client.mintToken(sessionId: sessionId)
        try SharedKeychain.setAuthToken(token.jwt, expiresAt: token.expiresAt)
        os_log("auth UI → token written, reporting .authorized", log: Self.log, type: .default)
        await MainActor.run { self.finish(.authorized) }
      } catch {
        await self.showError(error, fallback: LoginCopy.invalidCode)
      }
    }
  }

  private func resendCode() {
    guard let prepared else { return }
    setSubmitting(true)
    errorMessage = nil
    otpErrorLabel.text = nil

    Task {
      do {
        try await client.prepareFirstFactor(signInId: prepared.signInId, phoneNumberId: prepared.phoneNumberId)
        await MainActor.run {
          self.setSubmitting(false)
          self.startCooldownTimer(seconds: 90)
        }
      } catch {
        await self.showError(error, fallback: LoginCopy.failedToResend)
      }
    }
  }

  // MARK: - Error mapping (mirrors use-login-flow.ts → mapClerkError)

  private func mapClerkError(_ error: Error) -> String? {
    guard case let .api(api?, _) = (error as? ClerkFrontendClient.ClerkError) else { return nil }
    let code = (api.code ?? "").lowercased()
    let msg = (api.message ?? "").lowercased()

    if code.contains("identifier") || code.contains("phone_number")
        || msg.contains("identifier is invalid") || msg.contains("invalid phone") {
      return LoginCopy.invalidPhoneSimple
    }
    if code == "verification_code_rate_limit_exceeded" {
      return LoginCopy.verificationCodeRateLimitExceeded
    }
    if code.contains("code") || msg.contains("code") {
      return LoginCopy.invalidCode
    }
    return nil
  }

  // MARK: - UI helpers

  @MainActor private func showError(_ error: Error, fallback: String) {
    setSubmitting(false)
    let message = mapClerkError(error) ?? fallback
    errorMessage = message
    switch phase {
    case .phone:
      phoneInputRow.hasError = true
      phoneErrorLabel.text = message
    case .otp:
      otpErrorLabel.text = message
      otpValue = ""
      otpCellsView.setText("")
    }
  }

  private func setSubmitting(_ submitting: Bool) {
    isSubmitting = submitting
    if submitting { spinner.startAnimating() } else { spinner.stopAnimating() }
    phoneInputRow.isEnabled = !submitting
    otpCellsView.setEnabled(!submitting)
    primaryButton.setLoading(submitting)
    let ready = phoneDigits.count == selectedCountry.digits && !submitting
    primaryButton.setEnabledState(ready)
  }

  // MARK: - Cooldown timer

  private func startCooldownTimer(seconds: Int) {
    stopCooldownTimer()
    cooldown = seconds
    renderResendLabel()
    cooldownTimer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { [weak self] _ in
      guard let self else { return }
      self.cooldown = max(0, self.cooldown - 1)
      self.renderResendLabel()
      if self.cooldown == 0 { self.stopCooldownTimer() }
    }
  }

  private func stopCooldownTimer() {
    cooldownTimer?.invalidate()
    cooldownTimer = nil
  }

  // MARK: - Completion

  private func finish(_ result: PKIssuerProvisioningExtensionAuthorizationResult) {
    guard !didComplete else { return }
    didComplete = true
    stopCooldownTimer()
    completionHandler?(result)
  }
}

// MARK: - Constants / formatters (ported from darbpay-mobile/lib/auth/login)

fileprivate let OTP_LENGTH = 6

fileprivate struct Country {
  let code: String
  let flag: String
  let digits: Int
  let placeholder: String
}

fileprivate let LOGIN_COUNTRIES: [Country] = [
  Country(code: "+966", flag: "🇸🇦", digits: 9, placeholder: "5X XXX XXXX"),
  Country(code: "+1", flag: "🇺🇸", digits: 10, placeholder: "XXX XXX XXXX"),
  Country(code: "+31", flag: "🇳🇱", digits: 9, placeholder: "6 XXXX XXXX"),
  Country(code: "+33", flag: "🇫🇷", digits: 9, placeholder: "X XX XX XX XX"),
]

/// Port of `formatters.ts → formatPhoneByCountry`. Inserts spaces so the
/// visible value reads naturally (`"50 123 4567"`, `"555 123 4567"`).
fileprivate func formatPhoneByCountry(_ digits: String, _ code: String) -> String {
  if code == "+1" {
    if digits.count <= 3 { return digits }
    if digits.count <= 6 { return "\(digits.prefix(3)) \(digits.dropFirst(3))" }
    let p1 = digits.prefix(3)
    let p2 = digits.dropFirst(3).prefix(3)
    let p3 = digits.dropFirst(6).prefix(4)
    return "\(p1) \(p2) \(p3)"
  }
  if digits.count <= 2 { return digits }
  if digits.count <= 5 { return "\(digits.prefix(2)) \(digits.dropFirst(2))" }
  let p1 = digits.prefix(2)
  let p2 = digits.dropFirst(2).prefix(3)
  let p3 = digits.dropFirst(5).prefix(4)
  return "\(p1) \(p2) \(p3)"
}

/// Port of `formatters.ts → formatTimer`. `90 → "01:30"`.
fileprivate func formatTimer(_ seconds: Int) -> String {
  String(format: "%02d:%02d", seconds / 60, seconds % 60)
}

// MARK: - Copy (mirrors darbpay-mobile/messages/en.json `login.*` / `common.*`)

fileprivate enum LoginCopy {
  static let phoneScreenTitle = "Type in your phone number"
  static let phoneScreenSubtitle = "We'll send you a code for a quick and secure log-in"
  static let continueLabel = "Continue"

  // Error copy
  static let invalidPhoneSimple = "Phone number is invalid"
  static let invalidCode = "Invalid verification code"
  static let failedToSendCode = "Failed to send verification code"
  static let failedToResend = "Failed to resend code"
  static let verificationCodeRateLimitExceeded = "Too many attempts. Please wait before requesting a new code."

  // OTP screen
  static let enterVerificationCode = "Enter verification code"
  static let otpInstruction = "We sent an SMS with a verification code to"
  static let resendCode = "Resend Code"
  /// "Resend verification code after %@" — RN template was `{{time}}`.
  static let resendCodeAfter = "Resend verification code after %@"

  // Terms line
  static let termsPrefix = "By continuing, you agree to our"
  static let termsLink = "T&Cs"
  static let termsMiddle = "and"
  static let privacyLink = "Privacy Policy."

  // Top bar
  static let languageLabel = "English"
}

fileprivate enum LoginURLs {
  static let terms = URL(string: "https://darbpay.com/legal")!
  static let privacy = URL(string: "https://darbpay.com/en/legal/#privacy-policy")!
}

// MARK: - Design tokens (mirror AppColors light theme)

@available(iOS 14.0, *)
fileprivate enum DarbColors {
  static let primary = UIColor(rgb: 0x0078FF)
  static let primaryForeground = UIColor(rgb: 0xF8FAFC)
  static let primaryTint = UIColor(rgb: 0xF0F7FF)
  static let background = UIColor.white
  static let backgroundSecondary = UIColor(rgb: 0xFAFAFA)
  static let foreground = UIColor(rgb: 0x020817)
  static let mutedForeground = UIColor(rgb: 0x64748B)
  static let borderLight = UIColor(rgb: 0xDDE3E6)
  static let destructive = UIColor(rgb: 0xEF4444)
}

fileprivate extension UIColor {
  convenience init(rgb: UInt32, alpha: CGFloat = 1) {
    self.init(
      red: CGFloat((rgb >> 16) & 0xFF) / 255,
      green: CGFloat((rgb >> 8) & 0xFF) / 255,
      blue: CGFloat(rgb & 0xFF) / 255,
      alpha: alpha
    )
  }
}

// MARK: - DarbLogoView

/// Renders the Darb wordmark from the Figma vector (two filled bezier paths,
/// viewBox 60.6667×56). Drawn directly in `draw(_:)` so the extension doesn't
/// need to ship a resource bundle. Scales aspect-fit into any frame.
@available(iOS 14.0, *)
fileprivate final class DarbLogoView: UIView {
  override init(frame: CGRect) {
    super.init(frame: frame)
    backgroundColor = .clear
    isOpaque = false
    contentMode = .redraw
  }
  required init?(coder: NSCoder) { fatalError("init(coder:) not supported") }

  override var intrinsicContentSize: CGSize { CGSize(width: 120, height: 48) }

  override func draw(_ rect: CGRect) {
    guard let ctx = UIGraphicsGetCurrentContext() else { return }
    let viewBox = CGSize(width: 60.6667, height: 56)
    let scale = min(rect.width / viewBox.width, rect.height / viewBox.height)
    let drawnSize = CGSize(width: viewBox.width * scale, height: viewBox.height * scale)
    ctx.saveGState()
    defer { ctx.restoreGState() }
    ctx.translateBy(x: (rect.width - drawnSize.width) / 2, y: (rect.height - drawnSize.height) / 2)
    ctx.scaleBy(x: scale, y: scale)

    DarbColors.primary.setFill()

    let p1 = UIBezierPath()
    p1.move(to: CGPoint(x: 55.1431, y: 21.7787))
    p1.addCurve(to: CGPoint(x: 46.2201, y: 16.5388),
                controlPoint1: CGPoint(x: 52.664, y: 19.2876),
                controlPoint2: CGPoint(x: 49.5792, y: 17.4771))
    p1.addLine(to: CGPoint(x: 44.7463, y: 16.1281))
    p1.addLine(to: CGPoint(x: 45.1252, y: 17.6179))
    p1.addCurve(to: CGPoint(x: 40.6562, y: 34.0301),
                controlPoint1: CGPoint(x: 46.6139, y: 23.4754),
                controlPoint2: CGPoint(x: 44.9014, y: 29.7615))
    p1.addCurve(to: CGPoint(x: 14.2332, y: 52.5677),
                controlPoint1: CGPoint(x: 32.9772, y: 41.7461),
                controlPoint2: CGPoint(x: 24.087, y: 47.9842))
    p1.addLine(to: CGPoint(x: 13.4516, y: 52.9304))
    p1.addLine(to: CGPoint(x: 14.7643, y: 56))
    p1.addLine(to: CGPoint(x: 47.7744, y: 56))
    p1.addLine(to: CGPoint(x: 55.149, y: 48.5898))
    p1.addCurve(to: CGPoint(x: 55.149, y: 21.7787),
                controlPoint1: CGPoint(x: 62.5058, y: 41.1975),
                controlPoint2: CGPoint(x: 62.5058, y: 29.1709))
    p1.close()
    p1.fill()

    let p2 = UIBezierPath()
    p2.move(to: CGPoint(x: 44.4152, y: 14.6773))
    p2.addCurve(to: CGPoint(x: 39.4808, y: 5.97808),
                controlPoint1: CGPoint(x: 43.5799, y: 11.3918),
                controlPoint2: CGPoint(x: 41.8734, y: 8.3822))
    p2.addCurve(to: CGPoint(x: 10.707, y: 5.97808),
                controlPoint1: CGPoint(x: 31.5483, y: -1.99269),
                controlPoint2: CGPoint(x: 18.6396, y: -1.99269))
    p2.addLine(to: CGPoint(x: 0, y: 16.7397))
    p2.addLine(to: CGPoint(x: 13.5262, y: 30.3311))
    p2.addLine(to: CGPoint(x: 15.4534, y: 30.3311))
    p2.addLine(to: CGPoint(x: 25.1969, y: 20.5407))
    p2.addCurve(to: CGPoint(x: 43.3174, y: 15.7594),
                controlPoint1: CGPoint(x: 29.9224, y: 15.7894),
                controlPoint2: CGPoint(x: 36.8675, y: 13.9578))
    p2.addLine(to: CGPoint(x: 44.7911, y: 16.1701))
    p2.addLine(to: CGPoint(x: 44.4122, y: 14.6803))
    p2.close()
    p2.fill()
  }
}

// MARK: - LanguagePill

/// Static "🌐  English" chip pinned to the top-right of the phone screen.
/// English-only per scope decision; rendered for visual parity with the RN
/// app's language toggle but not interactive in this iteration.
@available(iOS 14.0, *)
fileprivate final class LanguagePill: UIView {
  override init(frame: CGRect) {
    super.init(frame: frame)
    backgroundColor = DarbColors.backgroundSecondary
    layer.cornerRadius = 16

    let icon = UIImageView(image: UIImage(systemName: "globe"))
    icon.tintColor = DarbColors.mutedForeground
    icon.contentMode = .scaleAspectFit
    icon.translatesAutoresizingMaskIntoConstraints = false

    let label = UILabel()
    label.text = LoginCopy.languageLabel
    label.font = .systemFont(ofSize: 16, weight: .medium)
    label.textColor = DarbColors.foreground
    label.translatesAutoresizingMaskIntoConstraints = false

    addSubview(icon)
    addSubview(label)
    NSLayoutConstraint.activate([
      heightAnchor.constraint(equalToConstant: 32),
      icon.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 12),
      icon.centerYAnchor.constraint(equalTo: centerYAnchor),
      icon.widthAnchor.constraint(equalToConstant: 15),
      icon.heightAnchor.constraint(equalToConstant: 15),
      label.leadingAnchor.constraint(equalTo: icon.trailingAnchor, constant: 6),
      label.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -12),
      label.centerYAnchor.constraint(equalTo: centerYAnchor),
    ])
  }
  required init?(coder: NSCoder) { fatalError("init(coder:) not supported") }
}

// MARK: - PhoneInputRow

/// Country chip (tap to pick) + phone field, joined inside a single 14pt-radius
/// bordered container. Stores raw digits separately from the formatted display
/// so the caller can re-format on each change without fighting the cursor.
@available(iOS 14.0, *)
fileprivate final class PhoneInputRow: UIView, UITextFieldDelegate {
  fileprivate var country: Country? {
    didSet { updateCountry() }
  }

  /// Raw digits the user has typed (no spaces). `setFormattedText` is the
  /// inverse — the controller pushes the formatted display value back here.
  var rawDigits: String { (field.text ?? "").filter(\.isNumber) }

  var hasError: Bool = false { didSet { updateBorder() } }
  var isEnabled: Bool {
    get { field.isEnabled }
    set {
      field.isEnabled = newValue
      countryChip.isUserInteractionEnabled = newValue
      alpha = newValue ? 1 : 0.6
    }
  }

  private let onCountryTap: () -> Void
  private let onTextChange: () -> Void

  // UIButton (not bare UIView + tap gesture) so taps register reliably inside
  // the PassKit extension's hosting environment.
  private let countryChip: UIButton = {
    let b = UIButton(type: .custom)
    b.backgroundColor = .clear
    return b
  }()

  private let countryLabel: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 16, weight: .medium)
    l.textColor = DarbColors.foreground
    return l
  }()

  private let chevron: UIImageView = {
    let cfg = UIImage.SymbolConfiguration(pointSize: 12, weight: .semibold)
    let iv = UIImageView(image: UIImage(systemName: "chevron.down", withConfiguration: cfg))
    iv.tintColor = DarbColors.mutedForeground
    iv.contentMode = .scaleAspectFit
    return iv
  }()

  private let divider: UIView = {
    let v = UIView()
    v.backgroundColor = DarbColors.borderLight
    return v
  }()

  private let field: UITextField = {
    let f = UITextField()
    f.font = .systemFont(ofSize: 16, weight: .regular)
    f.textColor = DarbColors.foreground
    f.keyboardType = .phonePad
    f.textContentType = .telephoneNumber
    f.borderStyle = .none
    return f
  }()

  private let container: UIView = {
    let v = UIView()
    v.backgroundColor = DarbColors.background
    v.layer.cornerRadius = 14
    v.layer.borderWidth = 1
    return v
  }()

  init(onCountryTap: @escaping () -> Void, onTextChange: @escaping () -> Void) {
    self.onCountryTap = onCountryTap
    self.onTextChange = onTextChange
    super.init(frame: .zero)

    field.addTarget(self, action: #selector(textChanged), for: .editingChanged)
    field.addTarget(self, action: #selector(focusChanged), for: .editingDidBegin)
    field.addTarget(self, action: #selector(focusChanged), for: .editingDidEnd)
    field.delegate = self

    countryChip.addTarget(self, action: #selector(countryTapped), for: .touchUpInside)

    container.translatesAutoresizingMaskIntoConstraints = false
    countryChip.translatesAutoresizingMaskIntoConstraints = false
    countryLabel.translatesAutoresizingMaskIntoConstraints = false
    chevron.translatesAutoresizingMaskIntoConstraints = false
    divider.translatesAutoresizingMaskIntoConstraints = false
    field.translatesAutoresizingMaskIntoConstraints = false

    addSubview(container)
    container.addSubview(countryChip)
    countryChip.addSubview(countryLabel)
    countryChip.addSubview(chevron)
    container.addSubview(divider)
    container.addSubview(field)

    countryChip.setContentHuggingPriority(.required, for: .horizontal)
    countryChip.setContentCompressionResistancePriority(.required, for: .horizontal)
    field.setContentHuggingPriority(.defaultLow, for: .horizontal)
    field.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)

    NSLayoutConstraint.activate([
      container.topAnchor.constraint(equalTo: topAnchor),
      container.leadingAnchor.constraint(equalTo: leadingAnchor),
      container.trailingAnchor.constraint(equalTo: trailingAnchor),
      container.bottomAnchor.constraint(equalTo: bottomAnchor),
      container.heightAnchor.constraint(equalToConstant: 52),

      // Country chip is explicitly capped at ~28% of the row so the phone
      // field gets the rest of the width. Without this, the chip drifted to
      // ~50% on device even with content-hugging set — UIView has no
      // intrinsic content size, so chevron+label can float arbitrarily.
      countryChip.leadingAnchor.constraint(equalTo: container.leadingAnchor, constant: 12),
      countryChip.topAnchor.constraint(equalTo: container.topAnchor),
      countryChip.bottomAnchor.constraint(equalTo: container.bottomAnchor),
      countryChip.widthAnchor.constraint(equalTo: container.widthAnchor, multiplier: 0.28),

      countryLabel.leadingAnchor.constraint(equalTo: countryChip.leadingAnchor),
      countryLabel.centerYAnchor.constraint(equalTo: countryChip.centerYAnchor),

      chevron.leadingAnchor.constraint(equalTo: countryLabel.trailingAnchor, constant: 6),
      chevron.centerYAnchor.constraint(equalTo: countryChip.centerYAnchor),
      chevron.widthAnchor.constraint(equalToConstant: 12),
      chevron.heightAnchor.constraint(equalToConstant: 12),
      chevron.trailingAnchor.constraint(lessThanOrEqualTo: countryChip.trailingAnchor),

      divider.leadingAnchor.constraint(equalTo: countryChip.trailingAnchor, constant: 10),
      divider.topAnchor.constraint(equalTo: container.topAnchor, constant: 12),
      divider.bottomAnchor.constraint(equalTo: container.bottomAnchor, constant: -12),
      divider.widthAnchor.constraint(equalToConstant: 1),

      // Field fills the full container height so the tap target is the entire
      // right portion of the row, not just the 21pt baseline of the text.
      field.leadingAnchor.constraint(equalTo: divider.trailingAnchor, constant: 10),
      field.trailingAnchor.constraint(equalTo: container.trailingAnchor, constant: -12),
      field.topAnchor.constraint(equalTo: container.topAnchor),
      field.bottomAnchor.constraint(equalTo: container.bottomAnchor),
    ])

    updateBorder()
  }
  required init?(coder: NSCoder) { fatalError("init(coder:) not supported") }

  override func becomeFirstResponder() -> Bool { field.becomeFirstResponder() }
  @discardableResult override func resignFirstResponder() -> Bool { field.resignFirstResponder() }

  func setInputAccessoryView(_ view: UIView) {
    field.inputAccessoryView = view
  }

  func setFormattedText(_ text: String) {
    if field.text != text { field.text = text }
    refreshPlaceholder()
  }

  private func refreshPlaceholder() {
    guard let country else { return }
    field.attributedPlaceholder = NSAttributedString(
      string: country.placeholder,
      attributes: [.foregroundColor: DarbColors.mutedForeground]
    )
  }

  @objc private func countryTapped() { onCountryTap() }
  @objc private func textChanged() { onTextChange() }
  @objc private func focusChanged() { updateBorder() }

  private func updateCountry() {
    guard let country else { return }
    countryLabel.text = "\(country.flag)  \(country.code)"
    refreshPlaceholder()
  }

  private func updateBorder() {
    if hasError {
      container.layer.borderColor = DarbColors.destructive.cgColor
    } else if field.isFirstResponder {
      container.layer.borderColor = DarbColors.primary.cgColor
    } else {
      container.layer.borderColor = DarbColors.borderLight.cgColor
    }
  }
}

// MARK: - OtpCellsView

/// Row of N rounded OTP cells. A hidden `oneTimeCode` UITextField captures
/// input (so iOS Messages autofill still works); each visible cell mirrors
/// one character of its current value. The cell at the current cursor
/// position takes the focused (2pt primary) border.
@available(iOS 14.0, *)
fileprivate final class OtpCellsView: UIView, UITextFieldDelegate {
  let length: Int
  var onChange: ((String) -> Void)?
  var text: String { hiddenField.text ?? "" }

  private let stack = UIStackView()
  private var cells: [OtpCell] = []
  private let hiddenField = UITextField()

  init(length: Int) {
    self.length = length
    super.init(frame: .zero)

    stack.axis = .horizontal
    stack.spacing = 8
    stack.distribution = .fillEqually
    stack.translatesAutoresizingMaskIntoConstraints = false
    addSubview(stack)

    for _ in 0..<length {
      let cell = OtpCell()
      cells.append(cell)
      stack.addArrangedSubview(cell)
    }

    hiddenField.keyboardType = .numberPad
    hiddenField.textContentType = .oneTimeCode
    hiddenField.tintColor = .clear
    hiddenField.translatesAutoresizingMaskIntoConstraints = false
    hiddenField.alpha = 0.02
    hiddenField.addTarget(self, action: #selector(textChanged), for: .editingChanged)
    hiddenField.addTarget(self, action: #selector(focusChanged), for: .editingDidBegin)
    hiddenField.addTarget(self, action: #selector(focusChanged), for: .editingDidEnd)
    hiddenField.delegate = self
    addSubview(hiddenField)

    addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(tapped)))

    NSLayoutConstraint.activate([
      stack.topAnchor.constraint(equalTo: topAnchor),
      stack.bottomAnchor.constraint(equalTo: bottomAnchor),
      stack.leadingAnchor.constraint(equalTo: leadingAnchor),
      stack.trailingAnchor.constraint(equalTo: trailingAnchor),
      heightAnchor.constraint(equalToConstant: 48),
      // Width: 6 cells × 48pt + 5 gaps × 8pt = 328pt
      widthAnchor.constraint(equalToConstant: CGFloat(length) * 48 + CGFloat(length - 1) * 8),
      hiddenField.topAnchor.constraint(equalTo: topAnchor),
      hiddenField.leadingAnchor.constraint(equalTo: leadingAnchor),
      hiddenField.widthAnchor.constraint(equalToConstant: 1),
      hiddenField.heightAnchor.constraint(equalToConstant: 1),
    ])

    updateCells()
  }
  required init?(coder: NSCoder) { fatalError("init(coder:) not supported") }

  override func becomeFirstResponder() -> Bool { hiddenField.becomeFirstResponder() }
  @discardableResult override func resignFirstResponder() -> Bool { hiddenField.resignFirstResponder() }

  func setInputAccessoryView(_ view: UIView) {
    hiddenField.inputAccessoryView = view
  }

  func setText(_ value: String) {
    let trimmed = String(value.filter(\.isNumber).prefix(length))
    if hiddenField.text != trimmed {
      hiddenField.text = trimmed
    }
    updateCells()
  }

  func setEnabled(_ enabled: Bool) {
    hiddenField.isEnabled = enabled
    isUserInteractionEnabled = enabled
    alpha = enabled ? 1 : 0.6
  }

  @objc private func tapped() { _ = hiddenField.becomeFirstResponder() }

  @objc private func textChanged() {
    let trimmed = String((hiddenField.text ?? "").filter(\.isNumber).prefix(length))
    if hiddenField.text != trimmed { hiddenField.text = trimmed }
    updateCells()
    onChange?(trimmed)
  }

  @objc private func focusChanged() { updateCells() }

  private func updateCells() {
    let chars = Array(text)
    let focusIdx = min(chars.count, length - 1)
    for (i, cell) in cells.enumerated() {
      cell.digit = i < chars.count ? String(chars[i]) : nil
      cell.isCellFocused = hiddenField.isFirstResponder && i == focusIdx
    }
  }
}

@available(iOS 14.0, *)
fileprivate final class OtpCell: UIView {
  var digit: String? { didSet { label.text = digit } }
  var isCellFocused: Bool = false { didSet { updateStyle() } }

  private let label: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 18, weight: .semibold)
    l.textColor = DarbColors.foreground
    l.textAlignment = .center
    return l
  }()

  override init(frame: CGRect) {
    super.init(frame: frame)
    layer.cornerRadius = 12
    layer.borderWidth = 1
    layer.borderColor = DarbColors.borderLight.cgColor
    backgroundColor = DarbColors.background
    label.translatesAutoresizingMaskIntoConstraints = false
    addSubview(label)
    NSLayoutConstraint.activate([
      label.centerXAnchor.constraint(equalTo: centerXAnchor),
      label.centerYAnchor.constraint(equalTo: centerYAnchor),
      widthAnchor.constraint(equalToConstant: 48),
      heightAnchor.constraint(equalToConstant: 48),
    ])
  }
  required init?(coder: NSCoder) { fatalError("init(coder:) not supported") }

  private func updateStyle() {
    layer.borderColor = (isCellFocused ? DarbColors.primary : DarbColors.borderLight).cgColor
    layer.borderWidth = isCellFocused ? 2 : 1
  }
}

// MARK: - PillButton (Continue)

/// Full-width fully-rounded pill button. Enabled state is solid `primary`
/// (`#0078FF`) at full opacity; disabled state animates to opacity 0.4 so the
/// user sees the moment their phone number becomes valid.
@available(iOS 14.0, *)
fileprivate final class PillButton: UIControl {
  var title: String = "" {
    didSet { label.text = title }
  }

  private let label: UILabel = {
    let l = UILabel()
    l.font = .systemFont(ofSize: 16, weight: .medium)
    l.textColor = DarbColors.primaryForeground
    l.textAlignment = .center
    return l
  }()

  private let loadingSpinner: UIActivityIndicatorView = {
    let s = UIActivityIndicatorView(style: .medium)
    s.color = DarbColors.primaryForeground
    s.hidesWhenStopped = true
    return s
  }()

  override init(frame: CGRect) {
    super.init(frame: frame)
    backgroundColor = DarbColors.primary
    clipsToBounds = true

    label.translatesAutoresizingMaskIntoConstraints = false
    loadingSpinner.translatesAutoresizingMaskIntoConstraints = false
    addSubview(label)
    addSubview(loadingSpinner)
    label.isUserInteractionEnabled = false
    loadingSpinner.isUserInteractionEnabled = false

    NSLayoutConstraint.activate([
      label.centerXAnchor.constraint(equalTo: centerXAnchor),
      label.centerYAnchor.constraint(equalTo: centerYAnchor),
      loadingSpinner.centerXAnchor.constraint(equalTo: centerXAnchor),
      loadingSpinner.centerYAnchor.constraint(equalTo: centerYAnchor),
    ])

    setEnabledState(false)
  }
  required init?(coder: NSCoder) { fatalError("init(coder:) not supported") }

  override func layoutSubviews() {
    super.layoutSubviews()
    layer.cornerRadius = bounds.height / 2
  }

  func setEnabledState(_ enabled: Bool) {
    isEnabled = enabled
    UIView.animate(withDuration: 0.15) {
      self.alpha = enabled ? 1 : 0.4
    }
  }

  func setLoading(_ loading: Bool) {
    label.isHidden = loading
    if loading {
      loadingSpinner.startAnimating()
    } else {
      loadingSpinner.stopAnimating()
    }
  }

  override var isHighlighted: Bool {
    didSet { alpha = isHighlighted ? 0.85 : (isEnabled ? 1 : 0.4) }
  }
}

