
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.expensify.wallet;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeWalletSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "RNWallet";

  public NativeWalletSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void checkWalletAvailability(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void ensureGoogleWalletInitialized(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getSecureWalletInfo(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getCardStatusBySuffix(String last4Digits, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getCardStatusByIdentifier(String identifier, String tsp, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void canAddCardWithIdentifier(String identifier, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void debugPassLibraryState(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void addCardToGoogleWallet(ReadableMap cardData, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void resumeAddCardToGoogleWallet(ReadableMap cardData, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void listTokens(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void IOSPresentAddPaymentPassView(ReadableMap cardData, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void IOSHandleAddPaymentPassResponse(ReadableMap payload, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void addListener(String eventType);

  @ReactMethod
  @DoNotStrip
  public abstract void removeListeners(double count);
}
